### ISSUE TITLE
Better track Matlab

### ISSUE THREAD

**Issue by pv33** [ivapylibs/Lie#1]
Why does class structure not track Matlab?  There should be a ``Lie.group.SE2.homog``

Also why is there a Lie within  Lie?  Is that necessary to create the right namespace for python?  
Does the namespace/packaging have to operate at the same level as the directory for the package name? Can you point me to the link where I can learn about this?

**Comment by varunm99** [comment]
As far as the folder "Lie" within the package, that is necessary to have the prefix "Lie" added to all of the files. Without this folder, after running ` pip install -e Lie` the import statement at the top of the code would be `import SE2` instead of `import Lie.SE2`. Both the Lie and Curves libraries follow this structure. 
Admittedly, the Control library does not, and I didn't want to change it because there was a lot of existing code in there which would break if I made that change. If you want I can make that change to control (making everything that imports controller.linear need to import control.controller.linear for example). 

This link is where I got that info from while making the library:
https://python-packaging.readthedocs.io/en/latest/minimal.html

**Comment by varunm99** [comment]
For the MATLAB vs Python structure, I thought it would be more convenient and descriptive to name the class SE2 since in Python you don't need to reference the class by the entire package name but just the class name. There would be some ambiguity if there were two classes named Homog in different packages if someone were to write
`from Lie.group.SE2 import Homog`. 

I can still refactor Python to match the MATLAB folder structure just to keep consistency.

**Comment by pv33** [comment]
@varunm99 
Except that they also play the role of a namespace and I don't want the full name to be masked out.  I actually like that the full spelling is needed ``Lie.group.SE2.homog`` because it exactly explains what the object is.  The fact that in Matlab a package and a namespace are intertwined is actually a plus to me.

The fact that python permits obscuring the naming actually annoys me.  

Also, there is more than one way to represent a Lie group, thus there needs to be a mechanism to permit that.  Instantiation should be at minimum ``SE2.homog`` thus python package import should never obscure beyond the group to the chosen representation.

I will have to read up on namespace versus packages in python because they don't operate in an intuitive manner. Or at least your choice of usage is counterintuitive.

Fundamentally the coding philosophy is that the names should explain what is going on so that documentation is minimally necessary and should live almost one step above pseudocode.  When you write a particular function, you should be describing it at some conceptual pseudocode level such that this specification ends up in the documentation.  Several lines of code should be self explanatory.

The above combined with the TDD/BDD (test driven development or behavior driven development) methodology and doxygen tags completes the documentation process for code.  Between the three exact operation of the codebse should be obvious.

Given the above in mind, please go reproduce exactly the Matlab organizational structure and namespaces. Please do not editorialize in the coding anymore.

Control is fine as is.  We can discuss python packaging and namespaces the next time we meet.

**Comment by varunm99** [comment]
Fixed in https://github.com/ivapylibs/Lie/commit/a61c724de67181e781519090750aa3fc81f8e935
